VARIABLE_METADATA = {
    "ndvi": {
        "source": "COPERNICUS/S2_SR_HARMONIZED",
        "native_resolution_m": 10,
        "calculation": "normalizedDifference(['B8','B4'])",
        "notes": "Uses Sentinel-2 NIR (B8) and red (B4) 10m bands.",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "5_day",
        "season_options": ["winter", "spring", "summer", "autumn", "annual"],
    },
    "fvc": {
        "source": "COPERNICUS/S2_SR_HARMONIZED",
        "native_resolution_m": 10,
        "calculation": "FVC = (NDVI - NDVI_soil) / (NDVI_veg - NDVI_soil)",
        "notes": "Seasonal NDVI median composite (B8/B4). NDVI_soil/veg use 5th/95th percentiles over the AOI; output clipped to [0, 1].",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "seasonal",
        "season_options": ["winter", "spring", "summer", "autumn", "annual"],
    },
    "ndmi": {
        "source": "COPERNICUS/S2_SR_HARMONIZED",
        "native_resolution_m": 20,
        "calculation": "normalizedDifference(['B8','B11'])",
        "notes": "Uses Sentinel-2 NIR (10m) and SWIR1 (20m); native grid is 20m.",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "5_day",
        "season_options": ["winter", "spring", "summer", "autumn", "annual"],
    },
    "msi": {
        "source": "COPERNICUS/S2_SR_HARMONIZED",
        "native_resolution_m": 20,
        "calculation": "B11 / B8",
        "notes": "Uses Sentinel-2 SWIR1 (20m) over NIR (10m); native grid is 20m.",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "5_day",
        "season_options": ["winter", "spring", "summer", "autumn", "annual"],
    },
    "bsi": {
        "source": "COPERNICUS/S2_SR_HARMONIZED",
        "native_resolution_m": 20,
        "calculation": "((B11 + B4) - (B8 + B2)) / ((B11 + B4) + (B8 + B2))",
        "notes": "Bare Soil Index (BSI) using Sentinel-2 SWIR1 (B11), red (B4), NIR (B8), blue (B2); output grid is 20m.",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "5_day",
        "season_options": ["winter", "spring", "summer", "autumn", "annual"],
    },
    "rgb": {
        "source": "Copernicus Data Space openEO (SENTINEL2_L1C)",
        "native_resolution_m": 10,
        "calculation": "Sentinel Hub L1C true color optimized (B04/B03/B02)",
        "notes": "Applies the Sentinel Hub true color optimized formula to L1C reflectance and outputs 8-bit RGBA for visualization.",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "5_day",
        "season_options": ["winter", "spring", "summer", "autumn", "static"],
    },
    "rgb_raw": {
        "source": "Copernicus Data Space openEO (SENTINEL2_L2A)",
        "native_resolution_m": 10,
        "calculation": "Sentinel-2 RGB (B04/B03/B02) at a single date",
        "notes": "Raw reflectance RGB (L2A). Closest image to rgb_date (OPENEO_RGB_DATE / rgb_date) within search window; defaults to mid-season date when not provided.",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "5_day",
        "season_options": ["winter", "spring", "summer", "autumn", "static"],
    },
    "swi": {
        "source": "Copernicus Land Monitoring Service (Soil Water Index)",
        "native_resolution_m": 1000,
        "calculation": "Exact daily SWI selection (optional temporal aggregation)",
        "notes": "Defaults to CGLS_SWI_V1_EUROPE (SWI_100); uses mid-season date when no exact date is provided.",
        "temporal_coverage": {"start_year": 2015, "end_year": "present"},
        "temporal_resolution": "daily_or_static",
        "season_options": ["winter", "spring", "summer", "autumn", "static"],
    },
    "alpha_earth": {
        "source": "GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL",
        "native_resolution_m": 10,
        "calculation": "Annual Alpha Earth embedding raster",
        "notes": "Annual embeddings produced by Google AlphaEarth; single yearly composite.",
        "temporal_coverage": {"start_year": 2017, "end_year": "present"},
        "temporal_resolution": "annual",
        "season_options": ["annual"],
    },
    "clcplus": {
        "source": "CLCplus (user-provided, one raster per country)",
        "native_resolution_m": 10,
        "calculation": "Manual ingestion of provided CLCplus classification raster",
        "notes": "Provide the local CLCplus folder; values 0 and nodata are remapped to -9999.",
        "temporal_coverage": {"start_year": 2018, "end_year": 2023},
        "temporal_resolution": "static",
        "season_options": ["annual"],
    },
    "bdod": {
        "source": "ISRIC SoilGrids 250m (file service)",
        "native_resolution_m": 250,
        "calculation": "Bulk density (bdod) mean",
        "notes": "Default depth 15-30cm mean; override with soilgrids_depth and soilgrids_stat.",
        "temporal_coverage": {"start_year": "static", "end_year": "static"},
        "temporal_resolution": "static",
        "season_options": ["annual"],
    },
    "clay": {
        "source": "ISRIC SoilGrids 250m (file service)",
        "native_resolution_m": 250,
        "calculation": "Clay content mean",
        "notes": "Default depth 15-30cm mean; override with soilgrids_depth and soilgrids_stat.",
        "temporal_coverage": {"start_year": "static", "end_year": "static"},
        "temporal_resolution": "static",
        "season_options": ["annual"],
    },
    "cfvo": {
        "source": "ISRIC SoilGrids 250m (file service)",
        "native_resolution_m": 250,
        "calculation": "Coarse fragments volume (cfvo) mean",
        "notes": "Default depth 15-30cm mean; override with soilgrids_depth and soilgrids_stat.",
        "temporal_coverage": {"start_year": "static", "end_year": "static"},
        "temporal_resolution": "static",
        "season_options": ["annual"],
    },
    "sand": {
        "source": "ISRIC SoilGrids 250m (file service)",
        "native_resolution_m": 250,
        "calculation": "Sand content mean",
        "notes": "Default depth 15-30cm mean; override with soilgrids_depth and soilgrids_stat.",
        "temporal_coverage": {"start_year": "static", "end_year": "static"},
        "temporal_resolution": "static",
        "season_options": ["annual"],
    },
    "silt": {
        "source": "ISRIC SoilGrids 250m (file service)",
        "native_resolution_m": 250,
        "calculation": "Silt content mean",
        "notes": "Default depth 15-30cm mean; override with soilgrids_depth and soilgrids_stat.",
        "temporal_coverage": {"start_year": "static", "end_year": "static"},
        "temporal_resolution": "static",
        "season_options": ["annual"],
    },
    "cec": {
        "source": "ISRIC SoilGrids 250m (file service)",
        "native_resolution_m": 250,
        "calculation": "Cation exchange capacity (cec) mean",
        "notes": "Default depth 15-30cm mean; override with soilgrids_depth and soilgrids_stat.",
        "temporal_coverage": {"start_year": "static", "end_year": "static"},
        "temporal_resolution": "static",
        "season_options": ["annual"],
    },
    "gbif_occurrences": {
        "source": "GBIF Occurrence API",
        "native_resolution_m": None,
        "calculation": "Occurrence point records filtered by AOI",
        "notes": "Includes species, taxonomic ranks (genus/family/order/class/phylum/kingdom), and eventDate/year when available. Defaults to full history (no date filter) with Animalia (Aves/Mammalia) and Plantae only.",
        "temporal_coverage": {"start_year": 1900, "end_year": "present"},
        "temporal_resolution": "event",
        "season_options": ["winter", "spring", "summer", "autumn", "annual"],
    },
}


def get_variable_metadata(name: str) -> dict:
    key = name.lower()
    return VARIABLE_METADATA.get(key, {})
